apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    spec:
      containers:
      - name: todoapp
        image: zevciu/todoapp
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
spec:
  selector:
    app: todoapp
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
